# load data 

In [35]:
import numpy as np

docs = []
for i in range(1, 60):
    name = 'dataset\\' + str(i)+'.txt'
    with open(name) as f:
        x = f.read()
        
        x = x.replace('\n', ' ')
        docs.append(x)
        f.close()
docs[0]



'Computer programming is the process of performing a particular computation (or more generally, accomplishing a specific computing result), usually by designing and building an executable computer program. Programming involves tasks such as analysis, generating algorithms, profiling algorithms\' accuracy and resource consumption, and the implementation of algorithms (usually in a chosen programming language, commonly referred to as coding).[1][2] The source code of a program is written in one or more languages that are intelligible to programmers, rather than machine code, which is directly executed by the central processing unit. The purpose of programming is to find a sequence of instructions that will automate the performance of a task (which can be as complex as an operating system) on a computer, often for solving a given problem. Proficient programming thus usually requires expertise in several different subjects, including knowledge of the application domain, specialized algorit

# inerted index


In [27]:
unique_terms = {term for doc in docs for term in doc.split()}
unique_terms


{'eyes.[3]',
 'classified',
 'https://www.trustedreviews.com',
 '1917.',
 'shortly',
 'spotted',
 'leasing',
 'heavy',
 'technologies',
 'Pre-Owned',
 '402',
 'targeting',
 'Listings',
 'means',
 'manga',
 'allow',
 'critically',
 'current',
 'War',
 'TV,',
 'programs,',
 'Films',
 'lender,',
 'Dental',
 'player',
 'ZIP',
 'their',
 'easier[15]',
 'high-level',
 'Cars.com’s',
 'people',
 'Boston',
 'tips',
 'collection',
 'Engineer',
 'airs',
 'In',
 'logic',
 'set',
 'prices',
 'film',
 'programmers',
 'Programming',
 'show',
 '26,',
 'without',
 'developing',
 'Netflix.',
 '16,',
 'SUBSCRIPTION',
 'many',
 'W.',
 'carriage.',
 'handling',
 'more,',
 'Thomas',
 'Elevated',
 'Instant',
 'implementation,',
 '2019.',
 '5.0%',
 'profile.',
 'automated',
 '...',
 'Hopper,',
 'bounce-demand',
 'sites',
 'price',
 'Distance',
 'changing',
 'origin.',
 'think',
 'CoMix',
 'kateoflahertyuk',
 'day.â€',
 'scene',
 '10',
 'Environmental',
 'Scientist',
 'frequency',
 'Series',
 'subcompact',
 

In [28]:
# Construct an inverted index

inverted_index = {}

for i, doc in enumerate(docs):

    for term in doc.split():
        if term in inverted_index:
            inverted_index[term].add(i)
        else:
            inverted_index[term] = {i}

inverted_index


{'Computer': {0},
 'programming': {0, 1, 2, 3, 6},
 'is': {0, 1, 3, 4, 5, 6, 7, 8},
 'the': {0, 1, 2, 3, 5, 6, 7, 8},
 'process': {0, 2},
 'of': {0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
 'performing': {0, 2},
 'a': {0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
 'particular': {0},
 'computation': {0},
 '(or': {0},
 'more': {0, 1, 3, 5, 7},
 'generally,': {0},
 'accomplishing': {0},
 'specific': {0},
 'computing': {0},
 'result),': {0},
 'usually': {0, 4, 5},
 'by': {0, 2, 4, 5, 6, 7},
 'designing': {0},
 'and': {0, 1, 3, 4, 5, 6, 7, 8, 9},
 'building': {0},
 'an': {0, 2, 4, 5, 6, 7, 9},
 'executable': {0},
 'computer': {0},
 'program.': {0},
 'Programming': {0},
 'involves': {0},
 'tasks': {0},
 'such': {0, 1, 3, 5, 8},
 'as': {0, 1, 2, 3, 5, 6, 7, 8},
 'analysis,': {0},
 'generating': {0},
 'algorithms,': {0},
 'profiling': {0},
 "algorithms'": {0},
 'accuracy': {0},
 'resource': {0},
 'consumption,': {0},
 'implementation': {0},
 'algorithms': {0},
 '(usually': {0},
 'in': {0, 1, 3, 4, 5, 6, 7, 8, 9},
 'cho

In [29]:
# test with computer, netflix , car , Anime, manga, Glassdoor, programming
posting_list = inverted_index['programming']
posting_list


{0, 1, 2, 3, 6}

In [30]:
def or_postings(posting1, posting2):
    # the prameters are lists
    p1 = 0
    p2 = 0
    result = list()
    while p1 < len(posting1) and p2 < len(posting2):

        if posting1[p1] == posting2[p2]:
            result.append(posting1[p1])
            p1 += 1
            p2 += 1
        elif posting1[p1] > posting2[p2]:
            result.append(posting2[p2])
            p2 += 1
        else:
            result.append(posting1[p1])
            p1 += 1

    while p1 < len(posting1):
        result.append(posting1[p1])
        p1 += 1
    while p2 < len(posting2):
        result.append(posting2[p2])
        p2 += 1
    return result


In [31]:
pl_1 = list(inverted_index['Anime'])
pl_2 = list(inverted_index['netflix'])
or_postings(pl_1, pl_2)


[1, 3, 4, 5]

In [32]:
def and_postings(posting1, posting2):
    p1 = 0
    p2 = 0
    result = list()
    while p1 < len(posting1) and p2 < len(posting2):
        if posting1[p1] == posting2[p2]:
            result.append(posting1[p1])
            p1 += 1
            p2 += 1
        elif posting1[p1] > posting2[p2]:
            p2 += 1
        else:
            p1 += 1
    return result


In [33]:
pl_1 = list(inverted_index['company'])
pl_2 = list(inverted_index['Glassdoor'])

and_postings(pl_1, pl_2)


[9]

# PIC quary

In [36]:
# google  djns

quary = input("Search: ")

docs.append(quary)
unique_terms.add(x for x in quary.split())
# -1 is quary

In [37]:
docs[-1]

'computer programmig'

# TF-IDF


In [38]:
# bag of words for each doc/file

bagofwords_list = []
cnt = 0
for doc in docs:
    bagofwords = doc.split(' ')
    if len(doc)<100:
        print(bagofwords)
    bagofwords_list.append(bagofwords)
    cnt+=1



['computer', 'programmig']


In [39]:
# count each word in all docs

numofword_list = []  # list of dictionaries
for i in range(11):
    temp = dict.fromkeys(unique_terms, 0)
    numofword_list.append(temp)

numofword_list[10]

{'eyes.[3]': 0,
 'classified': 0,
 'https://www.trustedreviews.com': 0,
 '1917.': 0,
 'shortly': 0,
 'spotted': 0,
 'leasing': 0,
 'heavy': 0,
 'technologies': 0,
 'Pre-Owned': 0,
 '402': 0,
 'targeting': 0,
 'Listings': 0,
 'means': 0,
 'manga': 0,
 'allow': 0,
 'critically': 0,
 'current': 0,
 'War': 0,
 'TV,': 0,
 'programs,': 0,
 'Films': 0,
 'lender,': 0,
 'Dental': 0,
 'player': 0,
 'ZIP': 0,
 'their': 0,
 'easier[15]': 0,
 'high-level': 0,
 'Cars.com’s': 0,
 'people': 0,
 'Boston': 0,
 'tips': 0,
 'collection': 0,
 'Engineer': 0,
 'airs': 0,
 'In': 0,
 'logic': 0,
 'set': 0,
 'prices': 0,
 'film': 0,
 'programmers': 0,
 'Programming': 0,
 'show': 0,
 '26,': 0,
 'without': 0,
 'developing': 0,
 'Netflix.': 0,
 '16,': 0,
 'SUBSCRIPTION': 0,
 'many': 0,
 'W.': 0,
 'carriage.': 0,
 'handling': 0,
 'more,': 0,
 'Thomas': 0,
 'Elevated': 0,
 'Instant': 0,
 'implementation,': 0,
 '2019.': 0,
 '5.0%': 0,
 'profile.': 0,
 'automated': 0,
 '...': 0,
 'Hopper,': 0,
 'bounce-demand': 0,
 

In [40]:
for i in range(11):
    bagofwords = bagofwords_list[i]
    for word in bagofwords:
        if word in numofword_list[i].keys():
            numofword_list[i][word] += 1
numofword_list[10]


{'eyes.[3]': 0,
 'classified': 0,
 'https://www.trustedreviews.com': 0,
 '1917.': 0,
 'shortly': 0,
 'spotted': 0,
 'leasing': 0,
 'heavy': 0,
 'technologies': 0,
 'Pre-Owned': 0,
 '402': 0,
 'targeting': 0,
 'Listings': 0,
 'means': 0,
 'manga': 0,
 'allow': 0,
 'critically': 0,
 'current': 0,
 'War': 0,
 'TV,': 0,
 'programs,': 0,
 'Films': 0,
 'lender,': 0,
 'Dental': 0,
 'player': 0,
 'ZIP': 0,
 'their': 0,
 'easier[15]': 0,
 'high-level': 0,
 'Cars.com’s': 0,
 'people': 0,
 'Boston': 0,
 'tips': 0,
 'collection': 0,
 'Engineer': 0,
 'airs': 0,
 'In': 0,
 'logic': 0,
 'set': 0,
 'prices': 0,
 'film': 0,
 'programmers': 0,
 'Programming': 0,
 'show': 0,
 '26,': 0,
 'without': 0,
 'developing': 0,
 'Netflix.': 0,
 '16,': 0,
 'SUBSCRIPTION': 0,
 'many': 0,
 'W.': 0,
 'carriage.': 0,
 'handling': 0,
 'more,': 0,
 'Thomas': 0,
 'Elevated': 0,
 'Instant': 0,
 'implementation,': 0,
 '2019.': 0,
 '5.0%': 0,
 'profile.': 0,
 'automated': 0,
 '...': 0,
 'Hopper,': 0,
 'bounce-demand': 0,
 

In [41]:
def computeTF(wordDict, bagOfWords):
    tfDict = {}
    bagOfWordsCount = len(bagOfWords)
    for word, count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
    return tfDict


In [42]:
TF_list = []
for i in range(10):
    tf = computeTF(numofword_list[i], bagofwords_list[i])
    TF_list.append(tf)
    
TF_list[0]


{'eyes.[3]': 0.0,
 'classified': 0.0,
 'https://www.trustedreviews.com': 0.0,
 '1917.': 0.0,
 'shortly': 0.0,
 'spotted': 0.0,
 'leasing': 0.0,
 'heavy': 0.0,
 'technologies': 0.0,
 'Pre-Owned': 0.0,
 '402': 0.0013003901170351106,
 'targeting': 0.0,
 'Listings': 0.0,
 'means': 0.0,
 'manga': 0.0,
 'allow': 0.0013003901170351106,
 'critically': 0.0,
 'current': 0.0,
 'War': 0.0,
 'TV,': 0.0,
 'programs,': 0.0013003901170351106,
 'Films': 0.0,
 'lender,': 0.0,
 'Dental': 0.0,
 'player': 0.0013003901170351106,
 'ZIP': 0.0,
 'their': 0.0,
 'easier[15]': 0.0013003901170351106,
 'high-level': 0.0013003901170351106,
 'Cars.com’s': 0.0,
 'people': 0.0,
 'Boston': 0.0,
 'tips': 0.0,
 'collection': 0.0,
 'Engineer': 0.0,
 'airs': 0.0,
 'In': 0.005201560468140442,
 'logic': 0.0013003901170351106,
 'set': 0.0013003901170351106,
 'prices': 0.0,
 'film': 0.0,
 'programmers': 0.002600780234070221,
 'Programming': 0.0013003901170351106,
 'show': 0.0,
 '26,': 0.0,
 'without': 0.0,
 'developing': 0.00

In [44]:
def computeIDF(documents):
    import math
    N = len(documents)

    idfDict = dict.fromkeys(documents[0].keys(), 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1

    for word, val in idfDict.items():
        if val ==0:
            val = .1
            
        idfDict[word] = math.log(N / float(val))
    return idfDict


In [45]:
IDFs = computeIDF(numofword_list)
IDFs


{'eyes.[3]': 1.7047480922384253,
 'classified': 1.7047480922384253,
 'https://www.trustedreviews.com': 2.3978952727983707,
 '1917.': 1.7047480922384253,
 'shortly': 2.3978952727983707,
 'spotted': 2.3978952727983707,
 'leasing': 2.3978952727983707,
 'heavy': 2.3978952727983707,
 'technologies': 2.3978952727983707,
 'Pre-Owned': 2.3978952727983707,
 '402': 2.3978952727983707,
 'targeting': 1.2992829841302609,
 'Listings': 2.3978952727983707,
 'means': 2.3978952727983707,
 'manga': 2.3978952727983707,
 'allow': 2.3978952727983707,
 'critically': 2.3978952727983707,
 'current': 1.7047480922384253,
 'War': 2.3978952727983707,
 'TV,': 2.3978952727983707,
 'programs,': 2.3978952727983707,
 'Films': 1.7047480922384253,
 'lender,': 2.3978952727983707,
 'Dental': 2.3978952727983707,
 'player': 2.3978952727983707,
 'ZIP': 2.3978952727983707,
 'their': 1.2992829841302609,
 'easier[15]': 2.3978952727983707,
 'high-level': 2.3978952727983707,
 'Cars.com’s': 2.3978952727983707,
 'people': 2.397895

In [46]:
def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf


In [47]:
TF_IDF_list = []
for i in range(10):
    temp = computeTFIDF(TF_list[i], IDFs)
    TF_IDF_list.append(temp)
TF_IDF_list


[{'eyes.[3]': 0.0,
  'classified': 0.0,
  'https://www.trustedreviews.com': 0.0,
  '1917.': 0.0,
  'shortly': 0.0,
  'spotted': 0.0,
  'leasing': 0.0,
  'heavy': 0.0,
  'technologies': 0.0,
  'Pre-Owned': 0.0,
  '402': 0.0031181993144322115,
  'targeting': 0.0,
  'Listings': 0.0,
  'means': 0.0,
  'manga': 0.0,
  'allow': 0.0031181993144322115,
  'critically': 0.0,
  'current': 0.0,
  'War': 0.0,
  'TV,': 0.0,
  'programs,': 0.0031181993144322115,
  'Films': 0.0,
  'lender,': 0.0,
  'Dental': 0.0,
  'player': 0.0031181993144322115,
  'ZIP': 0.0,
  'their': 0.0,
  'easier[15]': 0.0031181993144322115,
  'high-level': 0.0031181993144322115,
  'Cars.com’s': 0.0,
  'people': 0.0,
  'Boston': 0.0,
  'tips': 0.0,
  'collection': 0.0,
  'Engineer': 0.0,
  'airs': 0.0,
  'In': 0.0031528520341758933,
  'logic': 0.0031181993144322115,
  'set': 0.0031181993144322115,
  'prices': 0.0,
  'film': 0.0,
  'programmers': 0.006236398628864423,
  'Programming': 0.0031181993144322115,
  'show': 0.0,
  '2

In [48]:
import pandas as pd
df = pd.DataFrame(TF_IDF_list)
df.head()


eyes.[3]  classified  https://www.trustedreviews.com     1917.   shortly  \
0  0.000000    0.000000                             0.0  0.000000  0.000000   
1  0.005412    0.005412                             0.0  0.005412  0.000000   
2  0.000000    0.000000                             0.0  0.000000  0.000000   
3  0.005412    0.005412                             0.0  0.005412  0.000000   
4  0.000000    0.000000                             0.0  0.000000  0.023057   

   spotted  leasing  heavy  technologies  Pre-Owned  ...   "camera  \
0      0.0      0.0    0.0           0.0        0.0  ...  0.000000   
1      0.0      0.0    0.0           0.0        0.0  ...  0.005412   
2      0.0      0.0    0.0           0.0        0.0  ...  0.000000   
3      0.0      0.0    0.0           0.0        0.0  ...  0.005412   
4      0.0      0.0    0.0           0.0        0.0  ...  0.000000   

   technologies.  artifacts,  Deciphering  Brighthouse  automate   varied,  \
0       0.000000    0.003118     0.003118          0.0  0.003118  0.000000   
1       0.005412    0.000000     0.000000          0.0  0.000000  0.005412   
2       0.000000    0.000000     0.000000          0.0  0.000000  0.000000   
3       0.005412    0.000000     0.000000          0.0  0.000000  0.005412   
4       0.000000    0.000000     0.000000          0.0  0.000000  0.000000   

   good  you’re  sub-$10,000  
0   0.0       0.0          0.0  
1   0.0       0.0          0.0  
2   0.0       0.0          0.0  
3   0.0       0.0          0.0  
4   0.0       0.0          0.0  

[5 rows x 1547 columns]

In [23]:
print(df[1:])

   eyes.[3]  classified  https://www.trustedreviews.com     1917.   shortly  \
1  0.005412    0.005412                        0.000000  0.005412  0.000000   
2  0.000000    0.000000                        0.000000  0.000000  0.000000   
3  0.005412    0.005412                        0.000000  0.005412  0.000000   
4  0.000000    0.000000                        0.000000  0.000000  0.023057   
5  0.000000    0.000000                        0.004465  0.000000  0.000000   
6  0.000000    0.000000                        0.000000  0.000000  0.000000   
7  0.000000    0.000000                        0.000000  0.000000  0.000000   
8  0.000000    0.000000                        0.000000  0.000000  0.000000   
9  0.000000    0.000000                        0.000000  0.000000  0.000000   

    spotted   leasing     heavy  technologies  Pre-Owned  ...   "camera  \
1  0.000000  0.000000  0.000000      0.000000   0.000000  ...  0.005412   
2  0.000000  0.000000  0.000000      0.000000   0.000000  .

In [24]:
df[-1:]

eyes.[3]  classified  https://www.trustedreviews.com  1917.  shortly  \
9       0.0         0.0                             0.0    0.0      0.0   

   spotted  leasing  heavy  technologies  Pre-Owned  ...  "camera  \
9      0.0      0.0    0.0           0.0        0.0  ...      0.0   

   technologies.  artifacts,  Deciphering  Brighthouse  automate  varied,  \
9            0.0         0.0          0.0          0.0       0.0      0.0   

   good  you’re  sub-$10,000  
9   0.0       0.0          0.0  

[1 rows x 1547 columns]

In [25]:
from sklearn.metrics.pairwise import cosine_similarity
target =df[-1:]
csim_list = []
for i in range(len(df)-2):
    x = cosine_similarity(target,df[i:])
    csim_list .append(x)
csim_list

[array([[3.93175146e-03, 9.84023807e-03, 8.77501404e-04, 9.84023807e-03,
         3.41008709e-03, 2.10616071e-03, 1.22253233e-03, 1.64568689e-02,
         6.65535771e-04, 1.00000000e+00]]),
 array([[9.84023807e-03, 8.77501404e-04, 9.84023807e-03, 3.41008709e-03,
         2.10616071e-03, 1.22253233e-03, 1.64568689e-02, 6.65535771e-04,
         1.00000000e+00]]),
 array([[8.77501404e-04, 9.84023807e-03, 3.41008709e-03, 2.10616071e-03,
         1.22253233e-03, 1.64568689e-02, 6.65535771e-04, 1.00000000e+00]]),
 array([[9.84023807e-03, 3.41008709e-03, 2.10616071e-03, 1.22253233e-03,
         1.64568689e-02, 6.65535771e-04, 1.00000000e+00]]),
 array([[3.41008709e-03, 2.10616071e-03, 1.22253233e-03, 1.64568689e-02,
         6.65535771e-04, 1.00000000e+00]]),
 array([[2.10616071e-03, 1.22253233e-03, 1.64568689e-02, 6.65535771e-04,
         1.00000000e+00]]),
 array([[1.22253233e-03, 1.64568689e-02, 6.65535771e-04, 1.00000000e+00]]),
 array([[1.64568689e-02, 6.65535771e-04, 1.00000000e+00]])]

# Cosine similarty
